-- AlterTable
ALTER TABLE "Boat" ALTER COLUMN "laps" SET DEFAULT 0,
ALTER COLUMN "lapStart" DROP NOT NULL,
ALTER COLUMN "lapEnd" DROP NOT NULL,
ALTER COLUMN "lapTime" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "Class" ALTER COLUMN "handicap" SET DEFAULT 1;
